/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as NumbersRouteImport } from './routes/numbers'
import { Route as ListeningRouteImport } from './routes/listening'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as ClockRouteImport } from './routes/clock'
import { Route as AlphabetRouteImport } from './routes/alphabet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const NumbersRoute = NumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeningRoute = ListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockRoute = ClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphabetRoute = AlphabetRouteImport.update({
  id: '/alphabet',
  path: '/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LessonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alphabet': typeof AlphabetRoute
  '/clock': typeof ClockRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/listening': typeof ListeningRoute
  '/numbers': typeof NumbersRoute
  '/vocabulary': typeof VocabularyRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alphabet': typeof AlphabetRoute
  '/clock': typeof ClockRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/listening': typeof ListeningRoute
  '/numbers': typeof NumbersRoute
  '/vocabulary': typeof VocabularyRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alphabet': typeof AlphabetRoute
  '/clock': typeof ClockRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/listening': typeof ListeningRoute
  '/numbers': typeof NumbersRoute
  '/vocabulary': typeof VocabularyRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alphabet'
    | '/clock'
    | '/lessons'
    | '/listening'
    | '/numbers'
    | '/vocabulary'
    | '/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alphabet'
    | '/clock'
    | '/lessons'
    | '/listening'
    | '/numbers'
    | '/vocabulary'
    | '/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/alphabet'
    | '/clock'
    | '/lessons'
    | '/listening'
    | '/numbers'
    | '/vocabulary'
    | '/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlphabetRoute: typeof AlphabetRoute
  ClockRoute: typeof ClockRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  ListeningRoute: typeof ListeningRoute
  NumbersRoute: typeof NumbersRoute
  VocabularyRoute: typeof VocabularyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numbers': {
      id: '/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof NumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listening': {
      id: '/listening'
      path: '/listening'
      fullPath: '/listening'
      preLoaderRoute: typeof ListeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alphabet': {
      id: '/alphabet'
      path: '/alphabet'
      fullPath: '/alphabet'
      preLoaderRoute: typeof AlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof LessonsRoute
    }
  }
}

interface LessonsRouteChildren {
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsLessonIdRoute: LessonsLessonIdRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlphabetRoute: AlphabetRoute,
  ClockRoute: ClockRoute,
  LessonsRoute: LessonsRouteWithChildren,
  ListeningRoute: ListeningRoute,
  NumbersRoute: NumbersRoute,
  VocabularyRoute: VocabularyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
